### ISSUE TITLE
Package Dependency Issue in Version 1 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [gulp-community/gulp-footer#10]
The issue with the lodash dependency is still in version 1. It appears as though the update got pushed out to version 1 as well as version 2. The package dependency issue is a problem with version 1 still. If you could please fix it as soon as possible it would be greatly appreciated.

**Comment by mpriya05** [comment]
i am facing the same issue  with lodash depenedency. 

Error i am facing is 
Error: Cannot find module 'lodash._reinterpolate'[0m
> (/../ux/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/template.js:6:21)

Tempalte.js is using lodash._reinterpolate as dependecy, but this is not included in gulp-footer's package.json.

we  had our staging code verified two weeks back and things was working fine.. when we redeployed to plan for a production rollover, this is causing an issue. 

Could you please fix it ASAP. 
Appreciate your help.

**Comment by tracker1** [comment]
published as 1.1.2 sorry for the delay

Also, it looks like gulp-angular-templatecache is using a pinned version, so won't get any other than what they have specified.  I've submitted a PR to their repo for the update...

**Comment by blasky** [comment]
It appears I have 1.1.2 coming in through templatecache. But it fails to build with...

TypeError: undefined is not a function
  at .../node_modules/gulp-angular-templatecache/node_modules/gulp-footer/index.js:12:46

**Comment by tracker1** [comment]
@blasky what node version are you using?

**Comment by tracker1** [comment]
Closing as stale.
